### ISSUE TITLE
Invert the ApiService / other services pattern.

### ISSUE THREAD

**Issue by TheIronMarx** [MoonWolf125/2017MyriadMobileInternshipChallenge#2]
https://github.com/MoonWolf125/2017MyriadMobileInternshipChallenge/blob/fc41dc4e22247efdb2014084ac57bbc419790a89/dahnkyFinal/app/src/main/java/com/example/kl7304qk/dahnkyfinal/API/ApiService.java#L22

I like how you're dividing up services, but I think a safer, superior pattern would be to have your `ApiService` to be the Retrofit interface defining every call your application makes, and then your other services, `QuestService`, `KingdomService` etc. individually accessible to the pages which need it. 

The reasoning is this: if you want to make a network call for Kingdoms in your Kingdom list page, you'll have to pass in the `ApiService`, which would then grant that page access to all API calls available in your application, such as `getQuests()`, which it likely will never need. Generally, we want to shield classes from things they don't need, but make it easy to introduce them if the might need it. If instead your `ApiService` was your Retrofit interface as proposed above, you could instead pass in your `KingdomService` (which now has access to the `ApiService` to the Kingdom list page. This would only expose Kingdom-related things to that page. Then, if for some reason your Kingdom page also needed quests, it'd be as easy as bringing in the `QuestService` as you did the `KingdomService`. In code, I would then know at a glance what sort of things your page needed based on the services it depended on.

It all adds up to neater code.

**Comment by MoonWolf125** [comment]
I really like this suggestion. I've been questioning different ways to make one large API call in order to get all the information to reduce loading times for the ViewPagers. This may be a fault in my choice of ViewPagers, but I think I can shorten up some time by getting all the data after the kingdoms RecyclerView is shown and before one of them is clicked. Then just recall that data instead of having to call to the api every time I click a kingdom or quest.
